USE [master]
GO

/****** Object:  Database [EventManagement]    Script Date: 12/6/2019 3:23:56 PM ******/
CREATE DATABASE [EventManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EventManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EventManagement.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EventManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EventManagement_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULTu
GO

USE [EventManagement]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EventManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EventManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EventManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EventManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EventManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EventManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [EventManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EventManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EventManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EventManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EventManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EventManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EventManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EventManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EventManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EventManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EventManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EventManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EventManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EventManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EventManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EventManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EventManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EventManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [EventManagement] SET  MULTI_USER 
GO

ALTER DATABASE [EventManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EventManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EventManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EventManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EventManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EventManagement] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EventManagement] SET  READ_WRITE 
GO


