//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int commentId { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> postdate { get; set; }
        public int eventId { get; set; }
        public string userId { get; set; }
        public bool isInActive { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
